### ISSUE TITLE
Error windows 11 closes ps window

### ISSUE THREAD

**Issue by kaiserdj** [soruly/trace.moe-windows-menu#1]
When trying to find an image, a ps window opens but closes instantly

https://user-images.githubusercontent.com/5487950/134695231-9b1eacca-a56d-421b-8e79-68312bc48fe3.mp4

**Comment by soruly** [comment]
I haven't figured out a way to hide the powershell console when triggerring the powershell script.
However, a window should prompt as soon as the console close.
I haven't tested it on windows 11, I only tried this on a fresh windows 10.

**Comment by kaiserdj** [comment]
No window or error appears, I don't know if I can help you in any way

**Comment by soruly** [comment]
Can't reproduce this on Windows 11 as of now.
